---
name: 'build cpp'

on:
  push:
    branches:
    - '*'
jobs:
  build-linux-x86:
    # For Windows you can go with "windows-latest"
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Usually this is always needed
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib python3 curl zip unzip
      - name: version
        run: gcc --version
      - name: Build
        run: make
      - name: artifacts
        uses: actions/upload-artifact@v1
        with:
          name: linux-x64
          path: .
  build-macos-x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: version
        run: gcc --version
      - name: Build
        run: make
      - name: artifacts
        uses: actions/upload-artifact@v1
        with:
          name: macos-x64
          path: .