---
name: 'build cpp'

on:
  push:
    branches:
    - '*'
jobs:
  build-macos-x86:
    # For Windows you can go with "windows-latest"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2


      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib python3 curl zip unzip
      - name: verions
        run: gcc --version
      - name: Build
        run: make
      - name: artifacts
        uses: actions/upload-artifact@v1
        with:
          name: macos-x64
          path: .