---
name: 'build cpp macos x86'

on:
  push:
    branches:
    - '*'
jobs:
  build-macos-x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: version
        run: gcc --version
      - name: Build
        run: make
      - name: artifacts
        uses: actions/upload-artifact@v1
        with:
          name: macos-x64
          path: .